name: "WiFight Full Development Workflow"
description: "Complete development workflow from database to deployment"

version: "1.0"

triggers:
  - manual
  - schedule: "0 2 * * 0"  # Weekly on Sunday at 2 AM

variables:
  PROJECT_ROOT: "."
  BACKUP_DIR: "backups"
  TEST_MODE: false

phases:
  - name: "Phase 1: Foundation"
    description: "Database schema and API foundation"
    agents:
      - name: "database-agent"
        tasks:
          - id: "db-001"
            name: "Create database schema"
            required: true
          - id: "db-002"
            name: "Create migrations"
            required: true
          - id: "db-003"
            name: "Create seed data"
            required: true
            
      - name: "api-agent"
        tasks:
          - id: "api-001"
            name: "Create utility classes"
            required: true
            depends_on: ["db-001"]
          - id: "api-002"
            name: "Create auth endpoints"
            required: true
            depends_on: ["api-001"]
          - id: "api-003"
            name: "Create user endpoints"
            required: true
            depends_on: ["api-002"]
            
    validation:
      - type: "database"
        command: "mysql -u root -p < database/schema/complete-schema.sql"
      - type: "php-syntax"
        command: "php -l backend/**/*.php"
      - type: "composer"
        command: "composer validate"
        
  - name: "Phase 2: Controller Integration"
    description: "Integrate all controller types"
    depends_on: ["Phase 1: Foundation"]
    agents:
      - name: "controller-agent"
        tasks:
          - id: "ctrl-001"
            name: "Create Controller Abstraction Layer"
            required: true
          - id: "ctrl-002"
            name: "Implement MikroTik"
            required: true
            depends_on: ["ctrl-001"]
          - id: "ctrl-003"
            name: "Implement Omada"
            required: true
            depends_on: ["ctrl-001"]
          - id: "ctrl-004"
            name: "Implement Ruijie"
            required: true
            depends_on: ["ctrl-001"]
          - id: "ctrl-005"
            name: "Implement Meraki"
            required: true
            depends_on: ["ctrl-001"]
            
    validation:
      - type: "unit-tests"
        command: "vendor/bin/phpunit tests/controllers/"
      - type: "integration-tests"
        command: "vendor/bin/phpunit tests/integration/controllers/"
        
  - name: "Phase 3: Core Features"
    description: "Billing, sessions, subscriptions"
    depends_on: ["Phase 2: Controller Integration"]
    agents:
      - name: "api-agent"
        tasks:
          - id: "api-006"
            name: "Create session management"
            required: true
          - id: "api-007"
            name: "Create billing endpoints"
            required: true
          - id: "api-008"
            name: "Create payment integration"
            required: true
            
  - name: "Phase 4: Frontend"
    description: "Build user interfaces"
    depends_on: ["Phase 3: Core Features"]
    agents:
      - name: "frontend-agent"
        tasks:
          - id: "fe-001"
            name: "Create admin dashboard"
            required: true
          - id: "fe-002"
            name: "Create user portal"
            required: true
          - id: "fe-003"
            name: "Create captive portal"
            required: true
            
  - name: "Phase 5: Testing"
    description: "Comprehensive testing"
    depends_on: ["Phase 4: Frontend"]
    agents:
      - name: "testing-agent"
        tasks:
          - id: "test-001"
            name: "Unit tests"
            required: true
          - id: "test-002"
            name: "Integration tests"
            required: true
          - id: "test-003"
            name: "E2E tests"
            required: false
            
  - name: "Phase 6: Deployment"
    description: "Containerization and deployment"
    depends_on: ["Phase 5: Testing"]
    agents:
      - name: "devops-agent"
        tasks:
          - id: "devops-001"
            name: "Create Dockerfiles"
            required: true
          - id: "devops-002"
            name: "Create docker-compose"
            required: true
          - id: "devops-003"
            name: "Create CI/CD pipeline"
            required: true
          - id: "devops-004"
            name: "Create deployment scripts"
            required: true

notifications:
  on_success:
    - type: "console"
      message: "✓ Workflow completed successfully"
  on_failure:
    - type: "console"
      message: "✗ Workflow failed at phase: {phase}"
    - type: "log"
      file: "storage/logs/workflow-errors.log"

cleanup:
  - Remove temporary files
  - Clear cache
  - Generate final report